# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dtos.proto

require 'google/protobuf'


descriptor_data = "\n\ndtos.proto\x12\x06\x61rp.v1\"O\n\x11ProcessAudioInput\x12\x0e\n\x06\x62ucket\x18\x01 \x01(\t\x12\x11\n\taudio_key\x18\x02 \x01(\t\x12\x17\n\x0frecipient_email\x18\x03 \x01(\t\"4\n\x0fTranscribeInput\x12\x0e\n\x06\x62ucket\x18\x01 \x01(\t\x12\x11\n\taudio_key\x18\x02 \x01(\t\"*\n\x10TranscribeResult\x12\x16\n\x0etranscript_key\x18\x01 \x01(\t\"8\n\x0eSummarizeInput\x12\x0e\n\x06\x62ucket\x18\x01 \x01(\t\x12\x16\n\x0etranscript_key\x18\x02 \x01(\t\"&\n\x0fSummarizeResult\x12\x13\n\x0bsummary_key\x18\x01 \x01(\t\":\n\x10\x41\x63tionItemsInput\x12\x0e\n\x06\x62ucket\x18\x01 \x01(\t\x12\x16\n\x0etranscript_key\x18\x02 \x01(\t\"-\n\x11\x41\x63tionItemsResult\x12\x18\n\x10\x61\x63tion_items_key\x18\x01 \x01(\t\"|\n\nEmailInput\x12\x0e\n\x06\x62ucket\x18\x01 \x01(\t\x12\x16\n\x0etranscript_key\x18\x02 \x01(\t\x12\x13\n\x0bsummary_key\x18\x03 \x01(\t\x12\x18\n\x10\x61\x63tion_items_key\x18\x04 \x01(\t\x12\x17\n\x0frecipient_email\x18\x05 \x01(\t\"!\n\x0b\x45mailResult\x12\x12\n\nmessage_id\x18\x01 \x01(\tBk\n\rcom.arp.protoP\x01ZXgithub.com/anthonywittig/audio-recording-processor/services/summarize-go/gen/arpv1;arpv1b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Arp
  module V1
    ProcessAudioInput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("arp.v1.ProcessAudioInput").msgclass
    TranscribeInput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("arp.v1.TranscribeInput").msgclass
    TranscribeResult = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("arp.v1.TranscribeResult").msgclass
    SummarizeInput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("arp.v1.SummarizeInput").msgclass
    SummarizeResult = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("arp.v1.SummarizeResult").msgclass
    ActionItemsInput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("arp.v1.ActionItemsInput").msgclass
    ActionItemsResult = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("arp.v1.ActionItemsResult").msgclass
    EmailInput = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("arp.v1.EmailInput").msgclass
    EmailResult = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("arp.v1.EmailResult").msgclass
  end
end
