# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: summary.proto

require 'google/protobuf'


descriptor_data = "\n\rsummary.proto\x12\x06\x61rp.v1\"\x1a\n\x07Summary\x12\x0f\n\x07summary\x18\x01 \x01(\tBk\n\rcom.arp.protoP\x01ZXgithub.com/anthonywittig/audio-recording-processor/services/summarize-go/gen/arpv1;arpv1b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Arp
  module V1
    Summary = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("arp.v1.Summary").msgclass
  end
end
