// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: dtos.proto
// Protobuf Java Version: 4.35.1

package com.arp.proto;

@com.google.protobuf.Generated
public interface ActionItemsResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:arp.v1.ActionItemsResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string action_items_key = 1;</code>
   * @return The actionItemsKey.
   */
  java.lang.String getActionItemsKey();
  /**
   * <code>string action_items_key = 1;</code>
   * @return The bytes for actionItemsKey.
   */
  com.google.protobuf.ByteString
      getActionItemsKeyBytes();
}
