// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: dtos.proto
// Protobuf Java Version: 4.35.1

package com.arp.proto;

/**
 * Protobuf type {@code arp.v1.ActionItemsResult}
 */
@com.google.protobuf.Generated
public final class ActionItemsResult extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:arp.v1.ActionItemsResult)
    ActionItemsResultOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "ActionItemsResult");
  }
  // Use ActionItemsResult.newBuilder() to construct.
  private ActionItemsResult(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ActionItemsResult() {
    actionItemsKey_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.arp.proto.Dtos.internal_static_arp_v1_ActionItemsResult_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.arp.proto.Dtos.internal_static_arp_v1_ActionItemsResult_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.arp.proto.Dtos.internal_static_arp_v1_ActionItemsResult_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.arp.proto.ActionItemsResult.class, com.arp.proto.ActionItemsResult.Builder.class);
  }

  public static final int ACTION_ITEMS_KEY_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object actionItemsKey_ = "";
  /**
   * <code>string action_items_key = 1;</code>
   * @return The actionItemsKey.
   */
  @java.lang.Override
  public java.lang.String getActionItemsKey() {
    java.lang.Object ref = actionItemsKey_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      actionItemsKey_ = s;
      return s;
    }
  }
  /**
   * <code>string action_items_key = 1;</code>
   * @return The bytes for actionItemsKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getActionItemsKeyBytes() {
    java.lang.Object ref = actionItemsKey_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      actionItemsKey_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(actionItemsKey_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, actionItemsKey_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(actionItemsKey_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, actionItemsKey_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.arp.proto.ActionItemsResult)) {
      return super.equals(obj);
    }
    com.arp.proto.ActionItemsResult other = (com.arp.proto.ActionItemsResult) obj;

    if (!getActionItemsKey()
        .equals(other.getActionItemsKey())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ACTION_ITEMS_KEY_FIELD_NUMBER;
    hash = (53 * hash) + getActionItemsKey().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.arp.proto.ActionItemsResult parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.arp.proto.ActionItemsResult parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.arp.proto.ActionItemsResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.arp.proto.ActionItemsResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.arp.proto.ActionItemsResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.arp.proto.ActionItemsResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.arp.proto.ActionItemsResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.arp.proto.ActionItemsResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.arp.proto.ActionItemsResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.arp.proto.ActionItemsResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.arp.proto.ActionItemsResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.arp.proto.ActionItemsResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.arp.proto.ActionItemsResult prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code arp.v1.ActionItemsResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:arp.v1.ActionItemsResult)
      com.arp.proto.ActionItemsResultOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.arp.proto.Dtos.internal_static_arp_v1_ActionItemsResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.arp.proto.Dtos.internal_static_arp_v1_ActionItemsResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.arp.proto.ActionItemsResult.class, com.arp.proto.ActionItemsResult.Builder.class);
    }

    // Construct using com.arp.proto.ActionItemsResult.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      actionItemsKey_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.arp.proto.Dtos.internal_static_arp_v1_ActionItemsResult_descriptor;
    }

    @java.lang.Override
    public com.arp.proto.ActionItemsResult getDefaultInstanceForType() {
      return com.arp.proto.ActionItemsResult.getDefaultInstance();
    }

    @java.lang.Override
    public com.arp.proto.ActionItemsResult build() {
      com.arp.proto.ActionItemsResult result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.arp.proto.ActionItemsResult buildPartial() {
      com.arp.proto.ActionItemsResult result = new com.arp.proto.ActionItemsResult(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.arp.proto.ActionItemsResult result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.actionItemsKey_ = actionItemsKey_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.arp.proto.ActionItemsResult) {
        return mergeFrom((com.arp.proto.ActionItemsResult)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.arp.proto.ActionItemsResult other) {
      if (other == com.arp.proto.ActionItemsResult.getDefaultInstance()) return this;
      if (!other.getActionItemsKey().isEmpty()) {
        actionItemsKey_ = other.actionItemsKey_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              actionItemsKey_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object actionItemsKey_ = "";
    /**
     * <code>string action_items_key = 1;</code>
     * @return The actionItemsKey.
     */
    public java.lang.String getActionItemsKey() {
      java.lang.Object ref = actionItemsKey_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        actionItemsKey_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string action_items_key = 1;</code>
     * @return The bytes for actionItemsKey.
     */
    public com.google.protobuf.ByteString
        getActionItemsKeyBytes() {
      java.lang.Object ref = actionItemsKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        actionItemsKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string action_items_key = 1;</code>
     * @param value The actionItemsKey to set.
     * @return This builder for chaining.
     */
    public Builder setActionItemsKey(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      actionItemsKey_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string action_items_key = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearActionItemsKey() {
      actionItemsKey_ = getDefaultInstance().getActionItemsKey();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string action_items_key = 1;</code>
     * @param value The bytes for actionItemsKey to set.
     * @return This builder for chaining.
     */
    public Builder setActionItemsKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      actionItemsKey_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:arp.v1.ActionItemsResult)
  }

  // @@protoc_insertion_point(class_scope:arp.v1.ActionItemsResult)
  private static final com.arp.proto.ActionItemsResult DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.arp.proto.ActionItemsResult();
  }

  public static com.arp.proto.ActionItemsResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ActionItemsResult>
      PARSER = new com.google.protobuf.AbstractParser<ActionItemsResult>() {
    @java.lang.Override
    public ActionItemsResult parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ActionItemsResult> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ActionItemsResult> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.arp.proto.ActionItemsResult getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

