// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: dtos.proto
// Protobuf Java Version: 4.35.1

package com.arp.proto;

@com.google.protobuf.Generated
public interface BundleInputOrBuilder extends
    // @@protoc_insertion_point(interface_extends:arp.v1.BundleInput)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string bucket = 1;</code>
   * @return The bucket.
   */
  java.lang.String getBucket();
  /**
   * <code>string bucket = 1;</code>
   * @return The bytes for bucket.
   */
  com.google.protobuf.ByteString
      getBucketBytes();

  /**
   * <code>string transcript_key = 2;</code>
   * @return The transcriptKey.
   */
  java.lang.String getTranscriptKey();
  /**
   * <code>string transcript_key = 2;</code>
   * @return The bytes for transcriptKey.
   */
  com.google.protobuf.ByteString
      getTranscriptKeyBytes();

  /**
   * <code>string summary_key = 3;</code>
   * @return The summaryKey.
   */
  java.lang.String getSummaryKey();
  /**
   * <code>string summary_key = 3;</code>
   * @return The bytes for summaryKey.
   */
  com.google.protobuf.ByteString
      getSummaryKeyBytes();

  /**
   * <code>string action_items_key = 4;</code>
   * @return The actionItemsKey.
   */
  java.lang.String getActionItemsKey();
  /**
   * <code>string action_items_key = 4;</code>
   * @return The bytes for actionItemsKey.
   */
  com.google.protobuf.ByteString
      getActionItemsKeyBytes();
}
