// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: dtos.proto
// Protobuf Java Version: 4.35.1

package com.arp.proto;

/**
 * Protobuf type {@code arp.v1.BundleInput}
 */
@com.google.protobuf.Generated
public final class BundleInput extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:arp.v1.BundleInput)
    BundleInputOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "BundleInput");
  }
  // Use BundleInput.newBuilder() to construct.
  private BundleInput(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private BundleInput() {
    bucket_ = "";
    transcriptKey_ = "";
    summaryKey_ = "";
    actionItemsKey_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.arp.proto.Dtos.internal_static_arp_v1_BundleInput_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.arp.proto.Dtos.internal_static_arp_v1_BundleInput_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.arp.proto.Dtos.internal_static_arp_v1_BundleInput_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.arp.proto.BundleInput.class, com.arp.proto.BundleInput.Builder.class);
  }

  public static final int BUCKET_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object bucket_ = "";
  /**
   * <code>string bucket = 1;</code>
   * @return The bucket.
   */
  @java.lang.Override
  public java.lang.String getBucket() {
    java.lang.Object ref = bucket_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      bucket_ = s;
      return s;
    }
  }
  /**
   * <code>string bucket = 1;</code>
   * @return The bytes for bucket.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBucketBytes() {
    java.lang.Object ref = bucket_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      bucket_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TRANSCRIPT_KEY_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object transcriptKey_ = "";
  /**
   * <code>string transcript_key = 2;</code>
   * @return The transcriptKey.
   */
  @java.lang.Override
  public java.lang.String getTranscriptKey() {
    java.lang.Object ref = transcriptKey_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      transcriptKey_ = s;
      return s;
    }
  }
  /**
   * <code>string transcript_key = 2;</code>
   * @return The bytes for transcriptKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTranscriptKeyBytes() {
    java.lang.Object ref = transcriptKey_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      transcriptKey_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SUMMARY_KEY_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object summaryKey_ = "";
  /**
   * <code>string summary_key = 3;</code>
   * @return The summaryKey.
   */
  @java.lang.Override
  public java.lang.String getSummaryKey() {
    java.lang.Object ref = summaryKey_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      summaryKey_ = s;
      return s;
    }
  }
  /**
   * <code>string summary_key = 3;</code>
   * @return The bytes for summaryKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSummaryKeyBytes() {
    java.lang.Object ref = summaryKey_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      summaryKey_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ACTION_ITEMS_KEY_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object actionItemsKey_ = "";
  /**
   * <code>string action_items_key = 4;</code>
   * @return The actionItemsKey.
   */
  @java.lang.Override
  public java.lang.String getActionItemsKey() {
    java.lang.Object ref = actionItemsKey_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      actionItemsKey_ = s;
      return s;
    }
  }
  /**
   * <code>string action_items_key = 4;</code>
   * @return The bytes for actionItemsKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getActionItemsKeyBytes() {
    java.lang.Object ref = actionItemsKey_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      actionItemsKey_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(bucket_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, bucket_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(transcriptKey_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, transcriptKey_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(summaryKey_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, summaryKey_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(actionItemsKey_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, actionItemsKey_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(bucket_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, bucket_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(transcriptKey_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, transcriptKey_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(summaryKey_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, summaryKey_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(actionItemsKey_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, actionItemsKey_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.arp.proto.BundleInput)) {
      return super.equals(obj);
    }
    com.arp.proto.BundleInput other = (com.arp.proto.BundleInput) obj;

    if (!getBucket()
        .equals(other.getBucket())) return false;
    if (!getTranscriptKey()
        .equals(other.getTranscriptKey())) return false;
    if (!getSummaryKey()
        .equals(other.getSummaryKey())) return false;
    if (!getActionItemsKey()
        .equals(other.getActionItemsKey())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BUCKET_FIELD_NUMBER;
    hash = (53 * hash) + getBucket().hashCode();
    hash = (37 * hash) + TRANSCRIPT_KEY_FIELD_NUMBER;
    hash = (53 * hash) + getTranscriptKey().hashCode();
    hash = (37 * hash) + SUMMARY_KEY_FIELD_NUMBER;
    hash = (53 * hash) + getSummaryKey().hashCode();
    hash = (37 * hash) + ACTION_ITEMS_KEY_FIELD_NUMBER;
    hash = (53 * hash) + getActionItemsKey().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.arp.proto.BundleInput parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.arp.proto.BundleInput parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.arp.proto.BundleInput parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.arp.proto.BundleInput parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.arp.proto.BundleInput parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.arp.proto.BundleInput parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.arp.proto.BundleInput parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.arp.proto.BundleInput parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.arp.proto.BundleInput parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.arp.proto.BundleInput parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.arp.proto.BundleInput parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.arp.proto.BundleInput parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.arp.proto.BundleInput prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code arp.v1.BundleInput}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:arp.v1.BundleInput)
      com.arp.proto.BundleInputOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.arp.proto.Dtos.internal_static_arp_v1_BundleInput_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.arp.proto.Dtos.internal_static_arp_v1_BundleInput_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.arp.proto.BundleInput.class, com.arp.proto.BundleInput.Builder.class);
    }

    // Construct using com.arp.proto.BundleInput.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      bucket_ = "";
      transcriptKey_ = "";
      summaryKey_ = "";
      actionItemsKey_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.arp.proto.Dtos.internal_static_arp_v1_BundleInput_descriptor;
    }

    @java.lang.Override
    public com.arp.proto.BundleInput getDefaultInstanceForType() {
      return com.arp.proto.BundleInput.getDefaultInstance();
    }

    @java.lang.Override
    public com.arp.proto.BundleInput build() {
      com.arp.proto.BundleInput result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.arp.proto.BundleInput buildPartial() {
      com.arp.proto.BundleInput result = new com.arp.proto.BundleInput(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.arp.proto.BundleInput result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.bucket_ = bucket_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.transcriptKey_ = transcriptKey_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.summaryKey_ = summaryKey_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.actionItemsKey_ = actionItemsKey_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.arp.proto.BundleInput) {
        return mergeFrom((com.arp.proto.BundleInput)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.arp.proto.BundleInput other) {
      if (other == com.arp.proto.BundleInput.getDefaultInstance()) return this;
      if (!other.getBucket().isEmpty()) {
        bucket_ = other.bucket_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getTranscriptKey().isEmpty()) {
        transcriptKey_ = other.transcriptKey_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getSummaryKey().isEmpty()) {
        summaryKey_ = other.summaryKey_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getActionItemsKey().isEmpty()) {
        actionItemsKey_ = other.actionItemsKey_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              bucket_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              transcriptKey_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              summaryKey_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              actionItemsKey_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object bucket_ = "";
    /**
     * <code>string bucket = 1;</code>
     * @return The bucket.
     */
    public java.lang.String getBucket() {
      java.lang.Object ref = bucket_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        bucket_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string bucket = 1;</code>
     * @return The bytes for bucket.
     */
    public com.google.protobuf.ByteString
        getBucketBytes() {
      java.lang.Object ref = bucket_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        bucket_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string bucket = 1;</code>
     * @param value The bucket to set.
     * @return This builder for chaining.
     */
    public Builder setBucket(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      bucket_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string bucket = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearBucket() {
      bucket_ = getDefaultInstance().getBucket();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string bucket = 1;</code>
     * @param value The bytes for bucket to set.
     * @return This builder for chaining.
     */
    public Builder setBucketBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      bucket_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object transcriptKey_ = "";
    /**
     * <code>string transcript_key = 2;</code>
     * @return The transcriptKey.
     */
    public java.lang.String getTranscriptKey() {
      java.lang.Object ref = transcriptKey_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        transcriptKey_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string transcript_key = 2;</code>
     * @return The bytes for transcriptKey.
     */
    public com.google.protobuf.ByteString
        getTranscriptKeyBytes() {
      java.lang.Object ref = transcriptKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        transcriptKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string transcript_key = 2;</code>
     * @param value The transcriptKey to set.
     * @return This builder for chaining.
     */
    public Builder setTranscriptKey(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      transcriptKey_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string transcript_key = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTranscriptKey() {
      transcriptKey_ = getDefaultInstance().getTranscriptKey();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string transcript_key = 2;</code>
     * @param value The bytes for transcriptKey to set.
     * @return This builder for chaining.
     */
    public Builder setTranscriptKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      transcriptKey_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object summaryKey_ = "";
    /**
     * <code>string summary_key = 3;</code>
     * @return The summaryKey.
     */
    public java.lang.String getSummaryKey() {
      java.lang.Object ref = summaryKey_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        summaryKey_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string summary_key = 3;</code>
     * @return The bytes for summaryKey.
     */
    public com.google.protobuf.ByteString
        getSummaryKeyBytes() {
      java.lang.Object ref = summaryKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        summaryKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string summary_key = 3;</code>
     * @param value The summaryKey to set.
     * @return This builder for chaining.
     */
    public Builder setSummaryKey(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      summaryKey_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string summary_key = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSummaryKey() {
      summaryKey_ = getDefaultInstance().getSummaryKey();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string summary_key = 3;</code>
     * @param value The bytes for summaryKey to set.
     * @return This builder for chaining.
     */
    public Builder setSummaryKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      summaryKey_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object actionItemsKey_ = "";
    /**
     * <code>string action_items_key = 4;</code>
     * @return The actionItemsKey.
     */
    public java.lang.String getActionItemsKey() {
      java.lang.Object ref = actionItemsKey_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        actionItemsKey_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string action_items_key = 4;</code>
     * @return The bytes for actionItemsKey.
     */
    public com.google.protobuf.ByteString
        getActionItemsKeyBytes() {
      java.lang.Object ref = actionItemsKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        actionItemsKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string action_items_key = 4;</code>
     * @param value The actionItemsKey to set.
     * @return This builder for chaining.
     */
    public Builder setActionItemsKey(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      actionItemsKey_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string action_items_key = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearActionItemsKey() {
      actionItemsKey_ = getDefaultInstance().getActionItemsKey();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string action_items_key = 4;</code>
     * @param value The bytes for actionItemsKey to set.
     * @return This builder for chaining.
     */
    public Builder setActionItemsKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      actionItemsKey_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:arp.v1.BundleInput)
  }

  // @@protoc_insertion_point(class_scope:arp.v1.BundleInput)
  private static final com.arp.proto.BundleInput DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.arp.proto.BundleInput();
  }

  public static com.arp.proto.BundleInput getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BundleInput>
      PARSER = new com.google.protobuf.AbstractParser<BundleInput>() {
    @java.lang.Override
    public BundleInput parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<BundleInput> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BundleInput> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.arp.proto.BundleInput getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

