// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: dtos.proto
// Protobuf Java Version: 4.35.1

package com.arp.proto;

@com.google.protobuf.Generated
public interface BundleResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:arp.v1.BundleResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string bundle_key = 1;</code>
   * @return The bundleKey.
   */
  java.lang.String getBundleKey();
  /**
   * <code>string bundle_key = 1;</code>
   * @return The bytes for bundleKey.
   */
  com.google.protobuf.ByteString
      getBundleKeyBytes();
}
