// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: dtos.proto
// Protobuf Java Version: 4.35.1

package com.arp.proto;

@com.google.protobuf.Generated
public interface SummarizeResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:arp.v1.SummarizeResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string summary_key = 1;</code>
   * @return The summaryKey.
   */
  java.lang.String getSummaryKey();
  /**
   * <code>string summary_key = 1;</code>
   * @return The bytes for summaryKey.
   */
  com.google.protobuf.ByteString
      getSummaryKeyBytes();
}
