// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: transcript.proto
// Protobuf Java Version: 4.35.1

package com.arp.proto;

@com.google.protobuf.Generated
public final class TranscriptOuterClass extends com.google.protobuf.GeneratedFile {
  private TranscriptOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "TranscriptOuterClass");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_arp_v1_Transcript_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_arp_v1_Transcript_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_arp_v1_TranscriptSegment_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_arp_v1_TranscriptSegment_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020transcript.proto\022\006arp.v1\"l\n\nTranscript" +
      "\022\021\n\taudio_key\030\001 \001(\t\022\020\n\010language\030\002 \001(\t\022\014\n" +
      "\004text\030\003 \001(\t\022+\n\010segments\030\004 \003(\0132\031.arp.v1.T" +
      "ranscriptSegment\"X\n\021TranscriptSegment\022\017\n" +
      "\007speaker\030\001 \001(\t\022\022\n\nstart_time\030\002 \001(\001\022\020\n\010en" +
      "d_time\030\003 \001(\001\022\014\n\004text\030\004 \001(\tBk\n\rcom.arp.pr" +
      "otoP\001ZXgithub.com/anthonywittig/audio-re" +
      "cording-processor/services/summarize-go/" +
      "gen/arpv1;arpv1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_arp_v1_Transcript_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_arp_v1_Transcript_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_arp_v1_Transcript_descriptor,
        new java.lang.String[] { "AudioKey", "Language", "Text", "Segments", });
    internal_static_arp_v1_TranscriptSegment_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_arp_v1_TranscriptSegment_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_arp_v1_TranscriptSegment_descriptor,
        new java.lang.String[] { "Speaker", "StartTime", "EndTime", "Text", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
