// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: dtos.proto
// Protobuf Java Version: 4.35.1

package com.arp.proto;

@com.google.protobuf.Generated
public interface TranscribeResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:arp.v1.TranscribeResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string transcript_key = 1;</code>
   * @return The transcriptKey.
   */
  java.lang.String getTranscriptKey();
  /**
   * <code>string transcript_key = 1;</code>
   * @return The bytes for transcriptKey.
   */
  com.google.protobuf.ByteString
      getTranscriptKeyBytes();
}
