// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: transcript.proto
// Protobuf Java Version: 4.35.1

package com.arp.proto;

/**
 * <pre>
 * Normalized transcript: written by the transcribe worker (Java) and read by the
 * summarize (Go) and action-items (Python) workers. It is stored in S3 as
 * proto-JSON, so the on-disk file stays human-readable JSON while this .proto is
 * the single source of truth for the shape across the three languages.
 *
 * proto-JSON maps snake_case fields to lowerCamelCase JSON keys, so this emits
 * {"audioKey":..., "startTime":...} — identical to the previous hand-written
 * schema. Workers must marshal with default-value emission enabled and parse
 * with unknown fields ignored so all three languages agree byte-for-byte.
 * </pre>
 *
 * Protobuf type {@code arp.v1.Transcript}
 */
@com.google.protobuf.Generated
public final class Transcript extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:arp.v1.Transcript)
    TranscriptOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "Transcript");
  }
  // Use Transcript.newBuilder() to construct.
  private Transcript(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Transcript() {
    audioKey_ = "";
    language_ = "";
    text_ = "";
    segments_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.arp.proto.TranscriptOuterClass.internal_static_arp_v1_Transcript_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.arp.proto.TranscriptOuterClass.internal_static_arp_v1_Transcript_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.arp.proto.TranscriptOuterClass.internal_static_arp_v1_Transcript_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.arp.proto.Transcript.class, com.arp.proto.Transcript.Builder.class);
  }

  public static final int AUDIO_KEY_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object audioKey_ = "";
  /**
   * <code>string audio_key = 1;</code>
   * @return The audioKey.
   */
  @java.lang.Override
  public java.lang.String getAudioKey() {
    java.lang.Object ref = audioKey_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      audioKey_ = s;
      return s;
    }
  }
  /**
   * <code>string audio_key = 1;</code>
   * @return The bytes for audioKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAudioKeyBytes() {
    java.lang.Object ref = audioKey_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      audioKey_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LANGUAGE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object language_ = "";
  /**
   * <code>string language = 2;</code>
   * @return The language.
   */
  @java.lang.Override
  public java.lang.String getLanguage() {
    java.lang.Object ref = language_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      language_ = s;
      return s;
    }
  }
  /**
   * <code>string language = 2;</code>
   * @return The bytes for language.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getLanguageBytes() {
    java.lang.Object ref = language_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      language_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TEXT_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object text_ = "";
  /**
   * <code>string text = 3;</code>
   * @return The text.
   */
  @java.lang.Override
  public java.lang.String getText() {
    java.lang.Object ref = text_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      text_ = s;
      return s;
    }
  }
  /**
   * <code>string text = 3;</code>
   * @return The bytes for text.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTextBytes() {
    java.lang.Object ref = text_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      text_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SEGMENTS_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private java.util.List<com.arp.proto.TranscriptSegment> segments_;
  /**
   * <code>repeated .arp.v1.TranscriptSegment segments = 4;</code>
   */
  @java.lang.Override
  public java.util.List<com.arp.proto.TranscriptSegment> getSegmentsList() {
    return segments_;
  }
  /**
   * <code>repeated .arp.v1.TranscriptSegment segments = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.arp.proto.TranscriptSegmentOrBuilder> 
      getSegmentsOrBuilderList() {
    return segments_;
  }
  /**
   * <code>repeated .arp.v1.TranscriptSegment segments = 4;</code>
   */
  @java.lang.Override
  public int getSegmentsCount() {
    return segments_.size();
  }
  /**
   * <code>repeated .arp.v1.TranscriptSegment segments = 4;</code>
   */
  @java.lang.Override
  public com.arp.proto.TranscriptSegment getSegments(int index) {
    return segments_.get(index);
  }
  /**
   * <code>repeated .arp.v1.TranscriptSegment segments = 4;</code>
   */
  @java.lang.Override
  public com.arp.proto.TranscriptSegmentOrBuilder getSegmentsOrBuilder(
      int index) {
    return segments_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(audioKey_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, audioKey_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(language_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, language_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(text_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, text_);
    }
    for (int i = 0; i < segments_.size(); i++) {
      output.writeMessage(4, segments_.get(i));
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(audioKey_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, audioKey_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(language_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, language_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(text_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, text_);
    }

        {
          final int count = segments_.size();
          for (int i = 0; i < count; i++) {
            size += com.google.protobuf.CodedOutputStream
              .computeMessageSizeNoTag(segments_.get(i));
          }
          size += 1 * count;
        }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.arp.proto.Transcript)) {
      return super.equals(obj);
    }
    com.arp.proto.Transcript other = (com.arp.proto.Transcript) obj;

    if (!getAudioKey()
        .equals(other.getAudioKey())) return false;
    if (!getLanguage()
        .equals(other.getLanguage())) return false;
    if (!getText()
        .equals(other.getText())) return false;
    if (!getSegmentsList()
        .equals(other.getSegmentsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + AUDIO_KEY_FIELD_NUMBER;
    hash = (53 * hash) + getAudioKey().hashCode();
    hash = (37 * hash) + LANGUAGE_FIELD_NUMBER;
    hash = (53 * hash) + getLanguage().hashCode();
    hash = (37 * hash) + TEXT_FIELD_NUMBER;
    hash = (53 * hash) + getText().hashCode();
    if (getSegmentsCount() > 0) {
      hash = (37 * hash) + SEGMENTS_FIELD_NUMBER;
      hash = (53 * hash) + getSegmentsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.arp.proto.Transcript parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.arp.proto.Transcript parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.arp.proto.Transcript parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.arp.proto.Transcript parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.arp.proto.Transcript parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.arp.proto.Transcript parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.arp.proto.Transcript parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.arp.proto.Transcript parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.arp.proto.Transcript parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.arp.proto.Transcript parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.arp.proto.Transcript parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.arp.proto.Transcript parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.arp.proto.Transcript prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Normalized transcript: written by the transcribe worker (Java) and read by the
   * summarize (Go) and action-items (Python) workers. It is stored in S3 as
   * proto-JSON, so the on-disk file stays human-readable JSON while this .proto is
   * the single source of truth for the shape across the three languages.
   *
   * proto-JSON maps snake_case fields to lowerCamelCase JSON keys, so this emits
   * {"audioKey":..., "startTime":...} — identical to the previous hand-written
   * schema. Workers must marshal with default-value emission enabled and parse
   * with unknown fields ignored so all three languages agree byte-for-byte.
   * </pre>
   *
   * Protobuf type {@code arp.v1.Transcript}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:arp.v1.Transcript)
      com.arp.proto.TranscriptOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.arp.proto.TranscriptOuterClass.internal_static_arp_v1_Transcript_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.arp.proto.TranscriptOuterClass.internal_static_arp_v1_Transcript_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.arp.proto.Transcript.class, com.arp.proto.Transcript.Builder.class);
    }

    // Construct using com.arp.proto.Transcript.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      audioKey_ = "";
      language_ = "";
      text_ = "";
      if (segmentsBuilder_ == null) {
        segments_ = java.util.Collections.emptyList();
      } else {
        segments_ = null;
        segmentsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.arp.proto.TranscriptOuterClass.internal_static_arp_v1_Transcript_descriptor;
    }

    @java.lang.Override
    public com.arp.proto.Transcript getDefaultInstanceForType() {
      return com.arp.proto.Transcript.getDefaultInstance();
    }

    @java.lang.Override
    public com.arp.proto.Transcript build() {
      com.arp.proto.Transcript result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.arp.proto.Transcript buildPartial() {
      com.arp.proto.Transcript result = new com.arp.proto.Transcript(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.arp.proto.Transcript result) {
      if (segmentsBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          segments_ = java.util.Collections.unmodifiableList(segments_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.segments_ = segments_;
      } else {
        result.segments_ = segmentsBuilder_.build();
      }
    }

    private void buildPartial0(com.arp.proto.Transcript result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.audioKey_ = audioKey_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.language_ = language_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.text_ = text_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.arp.proto.Transcript) {
        return mergeFrom((com.arp.proto.Transcript)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.arp.proto.Transcript other) {
      if (other == com.arp.proto.Transcript.getDefaultInstance()) return this;
      if (!other.getAudioKey().isEmpty()) {
        audioKey_ = other.audioKey_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getLanguage().isEmpty()) {
        language_ = other.language_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getText().isEmpty()) {
        text_ = other.text_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (segmentsBuilder_ == null) {
        if (!other.segments_.isEmpty()) {
          if (segments_.isEmpty()) {
            segments_ = other.segments_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureSegmentsIsMutable();
            segments_.addAll(other.segments_);
          }
          onChanged();
        }
      } else {
        if (!other.segments_.isEmpty()) {
          if (segmentsBuilder_.isEmpty()) {
            segmentsBuilder_.dispose();
            segmentsBuilder_ = null;
            segments_ = other.segments_;
            bitField0_ = (bitField0_ & ~0x00000008);
            segmentsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetSegmentsFieldBuilder() : null;
          } else {
            segmentsBuilder_.addAllMessages(other.segments_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              audioKey_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              language_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              text_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              com.arp.proto.TranscriptSegment m =
                  input.readMessage(
                      com.arp.proto.TranscriptSegment.parser(),
                      extensionRegistry);
              if (segmentsBuilder_ == null) {
                ensureSegmentsIsMutable();
                segments_.add(m);
              } else {
                segmentsBuilder_.addMessage(m);
              }
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object audioKey_ = "";
    /**
     * <code>string audio_key = 1;</code>
     * @return The audioKey.
     */
    public java.lang.String getAudioKey() {
      java.lang.Object ref = audioKey_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        audioKey_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string audio_key = 1;</code>
     * @return The bytes for audioKey.
     */
    public com.google.protobuf.ByteString
        getAudioKeyBytes() {
      java.lang.Object ref = audioKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        audioKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string audio_key = 1;</code>
     * @param value The audioKey to set.
     * @return This builder for chaining.
     */
    public Builder setAudioKey(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      audioKey_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string audio_key = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearAudioKey() {
      audioKey_ = getDefaultInstance().getAudioKey();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string audio_key = 1;</code>
     * @param value The bytes for audioKey to set.
     * @return This builder for chaining.
     */
    public Builder setAudioKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      audioKey_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object language_ = "";
    /**
     * <code>string language = 2;</code>
     * @return The language.
     */
    public java.lang.String getLanguage() {
      java.lang.Object ref = language_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        language_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string language = 2;</code>
     * @return The bytes for language.
     */
    public com.google.protobuf.ByteString
        getLanguageBytes() {
      java.lang.Object ref = language_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        language_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string language = 2;</code>
     * @param value The language to set.
     * @return This builder for chaining.
     */
    public Builder setLanguage(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      language_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string language = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearLanguage() {
      language_ = getDefaultInstance().getLanguage();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string language = 2;</code>
     * @param value The bytes for language to set.
     * @return This builder for chaining.
     */
    public Builder setLanguageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      language_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object text_ = "";
    /**
     * <code>string text = 3;</code>
     * @return The text.
     */
    public java.lang.String getText() {
      java.lang.Object ref = text_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        text_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string text = 3;</code>
     * @return The bytes for text.
     */
    public com.google.protobuf.ByteString
        getTextBytes() {
      java.lang.Object ref = text_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        text_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string text = 3;</code>
     * @param value The text to set.
     * @return This builder for chaining.
     */
    public Builder setText(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      text_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string text = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearText() {
      text_ = getDefaultInstance().getText();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string text = 3;</code>
     * @param value The bytes for text to set.
     * @return This builder for chaining.
     */
    public Builder setTextBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      text_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.util.List<com.arp.proto.TranscriptSegment> segments_ =
      java.util.Collections.emptyList();
    private void ensureSegmentsIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        segments_ = new java.util.ArrayList<com.arp.proto.TranscriptSegment>(segments_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.arp.proto.TranscriptSegment, com.arp.proto.TranscriptSegment.Builder, com.arp.proto.TranscriptSegmentOrBuilder> segmentsBuilder_;

    /**
     * <code>repeated .arp.v1.TranscriptSegment segments = 4;</code>
     */
    public java.util.List<com.arp.proto.TranscriptSegment> getSegmentsList() {
      if (segmentsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(segments_);
      } else {
        return segmentsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .arp.v1.TranscriptSegment segments = 4;</code>
     */
    public int getSegmentsCount() {
      if (segmentsBuilder_ == null) {
        return segments_.size();
      } else {
        return segmentsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .arp.v1.TranscriptSegment segments = 4;</code>
     */
    public com.arp.proto.TranscriptSegment getSegments(int index) {
      if (segmentsBuilder_ == null) {
        return segments_.get(index);
      } else {
        return segmentsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .arp.v1.TranscriptSegment segments = 4;</code>
     */
    public Builder setSegments(
        int index, com.arp.proto.TranscriptSegment value) {
      if (segmentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSegmentsIsMutable();
        segments_.set(index, value);
        onChanged();
      } else {
        segmentsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .arp.v1.TranscriptSegment segments = 4;</code>
     */
    public Builder setSegments(
        int index, com.arp.proto.TranscriptSegment.Builder builderForValue) {
      if (segmentsBuilder_ == null) {
        ensureSegmentsIsMutable();
        segments_.set(index, builderForValue.build());
        onChanged();
      } else {
        segmentsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .arp.v1.TranscriptSegment segments = 4;</code>
     */
    public Builder addSegments(com.arp.proto.TranscriptSegment value) {
      if (segmentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSegmentsIsMutable();
        segments_.add(value);
        onChanged();
      } else {
        segmentsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .arp.v1.TranscriptSegment segments = 4;</code>
     */
    public Builder addSegments(
        int index, com.arp.proto.TranscriptSegment value) {
      if (segmentsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSegmentsIsMutable();
        segments_.add(index, value);
        onChanged();
      } else {
        segmentsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .arp.v1.TranscriptSegment segments = 4;</code>
     */
    public Builder addSegments(
        com.arp.proto.TranscriptSegment.Builder builderForValue) {
      if (segmentsBuilder_ == null) {
        ensureSegmentsIsMutable();
        segments_.add(builderForValue.build());
        onChanged();
      } else {
        segmentsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .arp.v1.TranscriptSegment segments = 4;</code>
     */
    public Builder addSegments(
        int index, com.arp.proto.TranscriptSegment.Builder builderForValue) {
      if (segmentsBuilder_ == null) {
        ensureSegmentsIsMutable();
        segments_.add(index, builderForValue.build());
        onChanged();
      } else {
        segmentsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .arp.v1.TranscriptSegment segments = 4;</code>
     */
    public Builder addAllSegments(
        java.lang.Iterable<? extends com.arp.proto.TranscriptSegment> values) {
      if (segmentsBuilder_ == null) {
        ensureSegmentsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, segments_);
        onChanged();
      } else {
        segmentsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .arp.v1.TranscriptSegment segments = 4;</code>
     */
    public Builder clearSegments() {
      if (segmentsBuilder_ == null) {
        segments_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        segmentsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .arp.v1.TranscriptSegment segments = 4;</code>
     */
    public Builder removeSegments(int index) {
      if (segmentsBuilder_ == null) {
        ensureSegmentsIsMutable();
        segments_.remove(index);
        onChanged();
      } else {
        segmentsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .arp.v1.TranscriptSegment segments = 4;</code>
     */
    public com.arp.proto.TranscriptSegment.Builder getSegmentsBuilder(
        int index) {
      return internalGetSegmentsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .arp.v1.TranscriptSegment segments = 4;</code>
     */
    public com.arp.proto.TranscriptSegmentOrBuilder getSegmentsOrBuilder(
        int index) {
      if (segmentsBuilder_ == null) {
        return segments_.get(index);  } else {
        return segmentsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .arp.v1.TranscriptSegment segments = 4;</code>
     */
    public java.util.List<? extends com.arp.proto.TranscriptSegmentOrBuilder> 
         getSegmentsOrBuilderList() {
      if (segmentsBuilder_ != null) {
        return segmentsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(segments_);
      }
    }
    /**
     * <code>repeated .arp.v1.TranscriptSegment segments = 4;</code>
     */
    public com.arp.proto.TranscriptSegment.Builder addSegmentsBuilder() {
      return internalGetSegmentsFieldBuilder().addBuilder(
          com.arp.proto.TranscriptSegment.getDefaultInstance());
    }
    /**
     * <code>repeated .arp.v1.TranscriptSegment segments = 4;</code>
     */
    public com.arp.proto.TranscriptSegment.Builder addSegmentsBuilder(
        int index) {
      return internalGetSegmentsFieldBuilder().addBuilder(
          index, com.arp.proto.TranscriptSegment.getDefaultInstance());
    }
    /**
     * <code>repeated .arp.v1.TranscriptSegment segments = 4;</code>
     */
    public java.util.List<com.arp.proto.TranscriptSegment.Builder> 
         getSegmentsBuilderList() {
      return internalGetSegmentsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.arp.proto.TranscriptSegment, com.arp.proto.TranscriptSegment.Builder, com.arp.proto.TranscriptSegmentOrBuilder> 
        internalGetSegmentsFieldBuilder() {
      if (segmentsBuilder_ == null) {
        segmentsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.arp.proto.TranscriptSegment, com.arp.proto.TranscriptSegment.Builder, com.arp.proto.TranscriptSegmentOrBuilder>(
                segments_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        segments_ = null;
      }
      return segmentsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:arp.v1.Transcript)
  }

  // @@protoc_insertion_point(class_scope:arp.v1.Transcript)
  private static final com.arp.proto.Transcript DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.arp.proto.Transcript();
  }

  public static com.arp.proto.Transcript getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Transcript>
      PARSER = new com.google.protobuf.AbstractParser<Transcript>() {
    @java.lang.Override
    public Transcript parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Transcript> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Transcript> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.arp.proto.Transcript getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

