// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: transcript.proto
// Protobuf Java Version: 4.35.1

package com.arp.proto;

@com.google.protobuf.Generated
public interface TranscriptSegmentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:arp.v1.TranscriptSegment)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string speaker = 1;</code>
   * @return The speaker.
   */
  java.lang.String getSpeaker();
  /**
   * <code>string speaker = 1;</code>
   * @return The bytes for speaker.
   */
  com.google.protobuf.ByteString
      getSpeakerBytes();

  /**
   * <code>double start_time = 2;</code>
   * @return The startTime.
   */
  double getStartTime();

  /**
   * <code>double end_time = 3;</code>
   * @return The endTime.
   */
  double getEndTime();

  /**
   * <code>string text = 4;</code>
   * @return The text.
   */
  java.lang.String getText();
  /**
   * <code>string text = 4;</code>
   * @return The bytes for text.
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
