// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: transcript.proto
// Protobuf Java Version: 4.35.1

package com.arp.proto;

@com.google.protobuf.Generated
public interface TranscriptOrBuilder extends
    // @@protoc_insertion_point(interface_extends:arp.v1.Transcript)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string audio_key = 1;</code>
   * @return The audioKey.
   */
  java.lang.String getAudioKey();
  /**
   * <code>string audio_key = 1;</code>
   * @return The bytes for audioKey.
   */
  com.google.protobuf.ByteString
      getAudioKeyBytes();

  /**
   * <code>string language = 2;</code>
   * @return The language.
   */
  java.lang.String getLanguage();
  /**
   * <code>string language = 2;</code>
   * @return The bytes for language.
   */
  com.google.protobuf.ByteString
      getLanguageBytes();

  /**
   * <code>string text = 3;</code>
   * @return The text.
   */
  java.lang.String getText();
  /**
   * <code>string text = 3;</code>
   * @return The bytes for text.
   */
  com.google.protobuf.ByteString
      getTextBytes();

  /**
   * <code>repeated .arp.v1.TranscriptSegment segments = 4;</code>
   */
  java.util.List<com.arp.proto.TranscriptSegment> 
      getSegmentsList();
  /**
   * <code>repeated .arp.v1.TranscriptSegment segments = 4;</code>
   */
  com.arp.proto.TranscriptSegment getSegments(int index);
  /**
   * <code>repeated .arp.v1.TranscriptSegment segments = 4;</code>
   */
  int getSegmentsCount();
  /**
   * <code>repeated .arp.v1.TranscriptSegment segments = 4;</code>
   */
  java.util.List<? extends com.arp.proto.TranscriptSegmentOrBuilder> 
      getSegmentsOrBuilderList();
  /**
   * <code>repeated .arp.v1.TranscriptSegment segments = 4;</code>
   */
  com.arp.proto.TranscriptSegmentOrBuilder getSegmentsOrBuilder(
      int index);
}
