// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: dtos.proto
// Protobuf Java Version: 4.35.1

package com.arp.proto;

@com.google.protobuf.Generated
public interface TranscribeInputOrBuilder extends
    // @@protoc_insertion_point(interface_extends:arp.v1.TranscribeInput)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string bucket = 1;</code>
   * @return The bucket.
   */
  java.lang.String getBucket();
  /**
   * <code>string bucket = 1;</code>
   * @return The bytes for bucket.
   */
  com.google.protobuf.ByteString
      getBucketBytes();

  /**
   * <code>string audio_key = 2;</code>
   * @return The audioKey.
   */
  java.lang.String getAudioKey();
  /**
   * <code>string audio_key = 2;</code>
   * @return The bytes for audioKey.
   */
  com.google.protobuf.ByteString
      getAudioKeyBytes();
}
