# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: action_items.proto

require 'google/protobuf'


descriptor_data = "\n\x12\x61\x63tion_items.proto\x12\x06\x61rp.v1\"#\n\x0b\x41\x63tionItems\x12\x14\n\x0c\x61\x63tion_items\x18\x01 \x03(\tBk\n\rcom.arp.protoP\x01ZXgithub.com/anthonywittig/audio-recording-processor/services/summarize-go/gen/arpv1;arpv1b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Arp
  module V1
    ActionItems = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("arp.v1.ActionItems").msgclass
  end
end
