# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bundle.proto

require 'google/protobuf'

require 'transcript_pb'
require 'summary_pb'
require 'action_items_pb'


descriptor_data = "\n\x0c\x62undle.proto\x12\x06\x61rp.v1\x1a\x10transcript.proto\x1a\rsummary.proto\x1a\x12\x61\x63tion_items.proto\"\x90\x01\n\x06\x42undle\x12\x11\n\taudio_key\x18\x01 \x01(\t\x12&\n\ntranscript\x18\x02 \x01(\x0b\x32\x12.arp.v1.Transcript\x12 \n\x07summary\x18\x03 \x01(\x0b\x32\x0f.arp.v1.Summary\x12)\n\x0c\x61\x63tion_items\x18\x04 \x01(\x0b\x32\x13.arp.v1.ActionItemsb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Arp
  module V1
    Bundle = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("arp.v1.Bundle").msgclass
  end
end
