# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transcript.proto

require 'google/protobuf'


descriptor_data = "\n\x10transcript.proto\x12\x06\x61rp.v1\"l\n\nTranscript\x12\x11\n\taudio_key\x18\x01 \x01(\t\x12\x10\n\x08language\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\t\x12+\n\x08segments\x18\x04 \x03(\x0b\x32\x19.arp.v1.TranscriptSegment\"X\n\x11TranscriptSegment\x12\x0f\n\x07speaker\x18\x01 \x01(\t\x12\x12\n\nstart_time\x18\x02 \x01(\x01\x12\x10\n\x08\x65nd_time\x18\x03 \x01(\x01\x12\x0c\n\x04text\x18\x04 \x01(\tBk\n\rcom.arp.protoP\x01ZXgithub.com/anthonywittig/audio-recording-processor/services/summarize-go/gen/arpv1;arpv1b\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Arp
  module V1
    Transcript = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("arp.v1.Transcript").msgclass
    TranscriptSegment = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("arp.v1.TranscriptSegment").msgclass
  end
end
