# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dtos.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'dtos.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndtos.proto\x12\x06\x61rp.v1\"<\n\x11ProcessAudioInput\x12\x0e\n\x06\x62ucket\x18\x01 \x01(\t\x12\x11\n\taudio_key\x18\x02 \x01(\tJ\x04\x08\x03\x10\x04\"4\n\x0fTranscribeInput\x12\x0e\n\x06\x62ucket\x18\x01 \x01(\t\x12\x11\n\taudio_key\x18\x02 \x01(\t\"*\n\x10TranscribeResult\x12\x16\n\x0etranscript_key\x18\x01 \x01(\t\"8\n\x0eSummarizeInput\x12\x0e\n\x06\x62ucket\x18\x01 \x01(\t\x12\x16\n\x0etranscript_key\x18\x02 \x01(\t\"&\n\x0fSummarizeResult\x12\x13\n\x0bsummary_key\x18\x01 \x01(\t\":\n\x10\x41\x63tionItemsInput\x12\x0e\n\x06\x62ucket\x18\x01 \x01(\t\x12\x16\n\x0etranscript_key\x18\x02 \x01(\t\"-\n\x11\x41\x63tionItemsResult\x12\x18\n\x10\x61\x63tion_items_key\x18\x01 \x01(\t\"d\n\x0b\x42undleInput\x12\x0e\n\x06\x62ucket\x18\x01 \x01(\t\x12\x16\n\x0etranscript_key\x18\x02 \x01(\t\x12\x13\n\x0bsummary_key\x18\x03 \x01(\t\x12\x18\n\x10\x61\x63tion_items_key\x18\x04 \x01(\t\"\"\n\x0c\x42undleResult\x12\x12\n\nbundle_key\x18\x01 \x01(\tBk\n\rcom.arp.protoP\x01ZXgithub.com/anthonywittig/audio-recording-processor/services/summarize-go/gen/arpv1;arpv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dtos_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\rcom.arp.protoP\001ZXgithub.com/anthonywittig/audio-recording-processor/services/summarize-go/gen/arpv1;arpv1'
  _globals['_PROCESSAUDIOINPUT']._serialized_start=22
  _globals['_PROCESSAUDIOINPUT']._serialized_end=82
  _globals['_TRANSCRIBEINPUT']._serialized_start=84
  _globals['_TRANSCRIBEINPUT']._serialized_end=136
  _globals['_TRANSCRIBERESULT']._serialized_start=138
  _globals['_TRANSCRIBERESULT']._serialized_end=180
  _globals['_SUMMARIZEINPUT']._serialized_start=182
  _globals['_SUMMARIZEINPUT']._serialized_end=238
  _globals['_SUMMARIZERESULT']._serialized_start=240
  _globals['_SUMMARIZERESULT']._serialized_end=278
  _globals['_ACTIONITEMSINPUT']._serialized_start=280
  _globals['_ACTIONITEMSINPUT']._serialized_end=338
  _globals['_ACTIONITEMSRESULT']._serialized_start=340
  _globals['_ACTIONITEMSRESULT']._serialized_end=385
  _globals['_BUNDLEINPUT']._serialized_start=387
  _globals['_BUNDLEINPUT']._serialized_end=487
  _globals['_BUNDLERESULT']._serialized_start=489
  _globals['_BUNDLERESULT']._serialized_end=523
# @@protoc_insertion_point(module_scope)
