// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               v7.35.1
// source: action_items.proto

/* eslint-disable */

export const protobufPackage = "arp.v1";

/**
 * Action items extracted from a transcript: written by action-items-py, read by
 * the web app. Stored in S3 as proto-JSON (=> {"actionItems": ["...", ...]}).
 */
export interface ActionItems {
  actionItems?: string[] | undefined;
}
