// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               v7.35.1
// source: bundle.proto

/* eslint-disable */
import type { ActionItems } from "./action_items";
import type { Summary } from "./summary";
import type { Transcript } from "./transcript";

export const protobufPackage = "arp.v1";

/**
 * The combined pipeline output: written by bundle-ruby as the workflow's last
 * step, embedding the three per-stage artifacts in one document. Stored in S3
 * as proto-JSON at bundles/<name>.bundle.json. Read by the web app, which uses
 * ts-proto-generated interfaces (types only) over the parsed JSON.
 */
export interface Bundle {
  audioKey?: string | undefined;
  transcript?: Transcript | undefined;
  summary?: Summary | undefined;
  actionItems?: ActionItems | undefined;
}
