// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               v7.35.1
// source: summary.proto

/* eslint-disable */

export const protobufPackage = "arp.v1";

/**
 * Transcript summary: written by summarize-go, read by the web app. Stored in
 * S3 as proto-JSON (=> {"summary": "..."}).
 */
export interface Summary {
  summary?: string | undefined;
}
