// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.12.0
//   protoc               v7.35.1
// source: transcript.proto

/* eslint-disable */

export const protobufPackage = "arp.v1";

/**
 * Normalized transcript: written by the transcribe worker (Java) and read by the
 * summarize (Go) and action-items (Python) workers. It is stored in S3 as
 * proto-JSON, so the on-disk file stays human-readable JSON while this .proto is
 * the single source of truth for the shape across the three languages.
 *
 * proto-JSON maps snake_case fields to lowerCamelCase JSON keys, so this emits
 * {"audioKey":..., "startTime":...} — identical to the previous hand-written
 * schema. Workers must marshal with default-value emission enabled and parse
 * with unknown fields ignored so all three languages agree byte-for-byte.
 */
export interface Transcript {
  audioKey?: string | undefined;
  language?: string | undefined;
  text?: string | undefined;
  segments?: TranscriptSegment[] | undefined;
}

export interface TranscriptSegment {
  speaker?: string | undefined;
  startTime?: number | undefined;
  endTime?: number | undefined;
  text?: string | undefined;
}
